$axure.loadCurrentPage({
  "url":"app_icon__.html",
  "generationDate":new Date(1395120472823.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a6632c21bb8d4563bfe10a451af69747",
    "type":"Axure:Page",
    "name":"app icon须知",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"87687791531e47b39b558be59603f612",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":21,
              "y":24},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28afec05282e41038b8bed2fdf616fa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":21,
                  "y":24},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bccf82df4cec463fbb80918ffd1e98e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":21,
              "y":50},
            "size":{
              "width":219,
              "height":243}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bde62e9965f40ed9d254671588d3742",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":21,
                  "y":50},
                "size":{
                  "width":219,
                  "height":243}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app_icon__/u2.png"}},
{
          "id":"a2f59d8279234991b42cac0a28e982e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":110,
              "y":350},
            "size":{
              "width":290,
              "height":255}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6662cd241ac34160a5cc29ba4e787d2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":110,
                  "y":350},
                "size":{
                  "width":290,
                  "height":255}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app_icon__/u4.png"}},
{
          "id":"ac80a07811eb4e80b54448657df47068",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":111,
              "y":324},
            "size":{
              "width":305,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c17c5d08b1f4b2e9119fc0766888e29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":111,
                  "y":324},
                "size":{
                  "width":305,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce63661bb5e84cc7b5fec2b129811734",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":440,
              "y":392},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a60fe393e2240ac860e281214dd1b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":392},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"579b4d42369849228569aa6a06e26231",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":260,
              "y":229},
            "size":{
              "width":300,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a00f698560ca47dd9e0c19b159f9d3c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":260,
                  "y":229},
                "size":{
                  "width":300,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "87687791531e47b39b558be59603f612":{
      "scriptId":"u0"},
    "28afec05282e41038b8bed2fdf616fa8":{
      "scriptId":"u1"},
    "bccf82df4cec463fbb80918ffd1e98e0":{
      "scriptId":"u2"},
    "8bde62e9965f40ed9d254671588d3742":{
      "scriptId":"u3"},
    "a2f59d8279234991b42cac0a28e982e6":{
      "scriptId":"u4"},
    "6662cd241ac34160a5cc29ba4e787d2b":{
      "scriptId":"u5"},
    "ac80a07811eb4e80b54448657df47068":{
      "scriptId":"u6"},
    "6c17c5d08b1f4b2e9119fc0766888e29":{
      "scriptId":"u7"},
    "ce63661bb5e84cc7b5fec2b129811734":{
      "scriptId":"u8"},
    "6a60fe393e2240ac860e281214dd1b51":{
      "scriptId":"u9"},
    "579b4d42369849228569aa6a06e26231":{
      "scriptId":"u10"},
    "a00f698560ca47dd9e0c19b159f9d3c7":{
      "scriptId":"u11"}}});